"use client";

import { useState } from "react";
import { registry } from "./examples/registry";
import { CodeBlock } from "./code-block";
import { OpenInButtons } from "./open-in-buttons";
import "./examples/docs-pitch-theme.css";

interface PitchPreviewProps {
  name: keyof typeof registry;
}

/**
 * Renders a live @pitchkit/react example by name, plus its read-only
 * source. MDX pages reference examples by name only
 * (`<PitchPreview name="scatter-basic" />`) rather than embedding JSX
 * directly — Fumadocs renders `.mdx` as a Server Component, and every
 * @pitchkit/react layer takes accessor *functions* as props, which can't
 * cross the Server->Client boundary. Each example under ./examples is
 * therefore its own standalone "use client" file that originates its
 * accessors internally; this component just looks the matching one up
 * (see ./examples/registry.ts, generated by
 * scripts/generate-examples-registry.mjs).
 *
 * The code panel starts collapsed behind a "View Code" button (shadcn/ui's
 * registry-preview pattern) — once expanded it stays expanded, since the
 * point is to get it out of the way until asked for, not to hide it again.
 */
export function PitchPreview({ name }: PitchPreviewProps) {
  const entry = registry[name];
  if (!entry) {
    throw new Error(`PitchPreview: unknown example "${name}"`);
  }

  const [expanded, setExpanded] = useState(false);
  const { Component, source } = entry;

  return (
    <div className="pitchkit-preview not-prose">
      <div className="pitchkit-preview__stage">
        <div className="pitchkit-preview__stage-inner pitchkit-docs-pitch">
          <Component />
        </div>
      </div>
      <div className="pitchkit-preview__toolbar">
        <OpenInButtons name={name} source={source} />
      </div>
      <div
        className={
          expanded ? "pitchkit-preview__code" : "pitchkit-preview__code pitchkit-preview__code--collapsed"
        }
      >
        <CodeBlock code={source} lang="tsx" />
        {!expanded && (
          <div className="pitchkit-preview__code-fade">
            <button type="button" className="pitchkit-preview__code-toggle" onClick={() => setExpanded(true)}>
              View Code
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
