"use client";

import { registry } from "./examples/registry";
import { CodeBlock } from "./code-block";
import "./examples/docs-pitch-theme.css";

interface PitchPreviewProps {
  name: keyof typeof registry;
}

/**
 * Renders a live @pitchkit/react example by name, plus its read-only
 * source. MDX pages reference examples by name only
 * (`<PitchPreview name="scatter-basic" />`) rather than embedding JSX
 * directly — Fumadocs renders `.mdx` as a Server Component, and every
 * @pitchkit/react layer takes accessor *functions* as props, which can't
 * cross the Server->Client boundary. Each example under ./examples is
 * therefore its own standalone "use client" file that originates its
 * accessors internally; this component just looks the matching one up
 * (see ./examples/registry.ts, generated by
 * scripts/generate-examples-registry.mjs).
 */
export function PitchPreview({ name }: PitchPreviewProps) {
  const entry = registry[name];
  if (!entry) {
    throw new Error(`PitchPreview: unknown example "${name}"`);
  }

  const { Component, source } = entry;

  return (
    <div className="pitchkit-preview not-prose">
      <div className="pitchkit-preview__stage">
        <div className="pitchkit-preview__stage-inner pitchkit-docs-pitch">
          <Component />
        </div>
      </div>
      <CodeBlock code={source} lang="tsx" />
    </div>
  );
}
